### ISSUE TITLE
Hobostove crashes at startup

### ISSUE THREAD

**Issue by Messenbrink** [smartlogic/hobostove#11]
I have configured Hobostove as described in the README and defined the room as followed:
- subdomain: https://mycompany.campfirenow.com/
  token: 123456789abcdefghijk
  room: Developers at Work

Is this the correct way to do it?

**Comment by oestrich** [comment]
Hobostove will prompt you to fill that in on first run. Subdomain field should only have `mycompany` in it, otherwise it looks good.
