### ISSUE TITLE
Messages won't show in Ubuntu Terminal

### ISSUE THREAD

**Issue by Messenbrink** [smartlogic/hobostove#12]
Chat messages won't show up in the window. This counts for both received and send messages. I can see what I type in the bottom field but when I send it it dissapears...but gets send anyways as I checked through the web client. All that shows up in the main window is if a person signs in/out.

I am running Ubuntu 14.04.1 LTS

**Comment by oestrich** [comment]
Is there space left for the message to appear and it's just not showing? I don't have an ubuntu machine so any further debugging will be helpful.

**Comment by oestrich** [comment]
Can you check your `~/.hobostove.log` file? It should have message logs in it.

**Comment by Messenbrink** [comment]
Hi, thx for your quick response. Here is a screenshot of the window in Ubunu. The TimeStamp you can see is from when another person entered the room.
![screenshot from 2014-09-01 09 32 41](https://cloud.githubusercontent.com/assets/2656679/4105451/5bcb03d2-31aa-11e4-84f4-1cc6213ce336.png)

The only error I can find in the log file is this:

F, [2014-08-27T08:58:26.774738 #9833] FATAL -- : #TerminalNotifier::UnsupportedPlatformError: terminal-notifier is only supported on Mac OS X 10.8, or higher.

Other than that the messages are logged in there as ´@body´.

**Comment by oestrich** [comment]
Can you download the latest source and run `bin/hobostove`? I added `libnotify` to the gemspec which should stop TerminalNotifier from being loaded. Hopefully it doesn't break OSX.

**Comment by Messenbrink** [comment]
Hi, sorry for the late reply. It seems like that issue has been fixed, thanks :)
