### ISSUE TITLE
Formatting is all Janky on a Mac

### ISSUE THREAD

**Issue by PaulOstazeski** [smartlogic/hobostove#7]

**Comment by PaulOstazeski** [comment]
Installing terminal-notifier fixes the jankieness.

**Comment by oestrich** [comment]
Updated the README to say it's required. I can also update bin/hobostove to detect Mac and quit if that gem isn't installed.

Unfortunately I couldn't figure out how to specify mac only runtime dependencies unless I did a c extension setup.
